In [13]:
import pandas as pd
import numpy as np

In [14]:
import fastf1

In [15]:
# Enable cache for faster data retrieval
fastf1.Cache.enable_cache('./cache') 

# Load a race session (e.g., 2023 British Grand Prix, Race)
session = fastf1.get_session(2023, 'Abu Dhabi Grand Prix', 'R')

# Load the session data
session.load(telemetry=False)

# Access session results
results = session.results

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.4.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
logger      WARNING 	Failed to load result data from Ergast!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
logger      WARNING 	Failed to add first lap time from Ergast!
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '4', '22', '14', '27', '11', '10', '44', '31', '18', '23', '3', '55', '20', '77', '24', '2']

In [16]:
results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,,Red Bull Racing,3671C6,,Max,Verstappen,Max Verstappen,...,NED,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
16,16,C LECLERC,LEC,,Ferrari,F91536,,Charles,Leclerc,Charles Leclerc,...,MON,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
81,81,O PIASTRI,PIA,,McLaren,F58020,,Oscar,Piastri,Oscar Piastri,...,AUS,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
63,63,G RUSSELL,RUS,,Mercedes,6CD3BF,,George,Russell,George Russell,...,GBR,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
4,4,L NORRIS,NOR,,McLaren,F58020,,Lando,Norris,Lando Norris,...,GBR,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
22,22,Y TSUNODA,TSU,,AlphaTauri,5E8FAA,,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
14,14,F ALONSO,ALO,,Aston Martin,358C75,,Fernando,Alonso,Fernando Alonso,...,ESP,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
27,27,N HULKENBERG,HUL,,Haas F1 Team,B6BABD,,Nico,Hulkenberg,Nico Hulkenberg,...,GER,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
11,11,S PEREZ,PER,,Red Bull Racing,3671C6,,Sergio,Perez,Sergio Perez,...,MEX,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
10,10,P GASLY,GAS,,Alpine,2293D1,,Pierre,Gasly,Pierre Gasly,...,FRA,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
44,44,L HAMILTON,HAM,,Mercedes,6CD3BF,,Lewis,Hamilton,Lewis Hamilton,...,GBR,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
31,31,E OCON,OCO,,Alpine,2293D1,,Esteban,Ocon,Esteban Ocon,...,FRA,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
18,18,L STROLL,STR,,Aston Martin,358C75,,Lance,Stroll,Lance Stroll,...,CAN,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
23,23,A ALBON,ALB,,Williams,37BEDD,,Alexander,Albon,Alexander Albon,...,THA,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
3,3,D RICCIARDO,RIC,,AlphaTauri,5E8FAA,,Daniel,Ricciardo,Daniel Ricciardo,...,AUS,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
55,55,C SAINZ,SAI,,Ferrari,F91536,,Carlos,Sainz,Carlos Sainz,...,ESP,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
20,20,K MAGNUSSEN,MAG,,Haas F1 Team,B6BABD,,Kevin,Magnussen,Kevin Magnussen,...,DEN,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
77,77,V BOTTAS,BOT,,Alfa Romeo,C92D4B,,Valtteri,Bottas,Valtteri Bottas,...,FIN,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
24,24,G ZHOU,ZHO,,Alfa Romeo,C92D4B,,Guanyu,Zhou,Guanyu Zhou,...,CHN,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN
2,2,L SARGEANT,SAR,,Williams,37BEDD,,Logan,Sargeant,Logan Sargeant,...,USA,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN

In [5]:
session.total_laps

58

In [12]:
results['Time']

1    NaT
4    NaT
81   NaT
16   NaT
55   NaT
63   NaT
44   NaT
23   NaT
14   NaT
10   NaT
27   NaT
18   NaT
31   NaT
2    NaT
11   NaT
22   NaT
24   NaT
21   NaT
20   NaT
77   NaT
Name: Time, dtype: timedelta64[ns]

In [32]:
session.event

RoundNumber                                                       20
Country                                                       Brazil
Location                                                   São Paulo
OfficialEventName    FORMULA 1 ROLEX GRANDE PRÊMIO DE SÃO PAULO 2023
EventDate                                        2023-11-05 00:00:00
EventName                                       São Paulo Grand Prix
EventFormat                                          sprint_shootout
Session1                                                  Practice 1
Session1Date                               2023-11-03 11:30:00-03:00
Session1DateUtc                                  2023-11-03 14:30:00
Session2                                                  Qualifying
Session2Date                               2023-11-03 15:00:00-03:00
Session2DateUtc                                  2023-11-03 18:00:00
Session3                                             Sprint Shootout
Session3Date                               2023-11-04 11:00:00-03:00
Session3DateUtc                                  2023-11-04 14:00:00
Session4                                                      Sprint
Session4Date                               2023-11-04 15:30:00-03:00
Session4DateUtc                                  2023-11-04 18:30:00
Session5                                                        Race
Session5Date                               2023-11-05 14:00:00-03:00
Session5DateUtc                                  2023-11-05 17:00:00
F1ApiSupport                                                    True
Name: 20, dtype: object

In [22]:
temp_result['Time']

1    0 days 01:25:16.938000
4    0 days 00:00:03.798000
44   0 days 00:00:06.783000
81   0 days 00:00:07.776000
63   0 days 00:00:11.206000
11   0 days 00:00:12.882000
14   0 days 00:00:17.193000
23   0 days 00:00:17.878000
16   0 days 00:00:18.689000
55   0 days 00:00:19.448000
2    0 days 00:00:23.632000
77   0 days 00:00:25.830000
27   0 days 00:00:26.663000
18   0 days 00:00:27.483000
24   0 days 00:00:29.820000
22   0 days 00:00:31.225000
21   0 days 00:00:33.128000
10                      NaT
20                      NaT
31                      NaT
Name: Time, dtype: timedelta64[ns]

In [26]:
def update_times(results):
    """
    Update the Time column in the race results DataFrame to reflect the complete race time for each driver.

    Parameters:
    results (pd.DataFrame): A DataFrame containing race results, including a Time column. The Time column
                            contains the complete time for the first-position driver and time differences
                            for other drivers.

    Returns:
    pd.DataFrame: The updated DataFrame where the Time column now contains the actual complete race time
                  for each driver.
    """
    if 'Time' not in results.columns or pd.isnull(results.iloc[0]['Time']):
        return results
    
    # Extract the time of the first-position driver
    base_time = results.iloc[0]['Time']
    
    # Update the Time column for all other drivers
    results['Time'] = results['Time'].apply(
        lambda x: base_time + x if pd.notnull(x) and x != base_time else x
    )
    return results

In [27]:
update_times(temp_result)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,1.0,NaT,NaT,NaT,0 days 01:25:16.938000,Finished,26.0
4,4,L NORRIS,NOR,norris,McLaren,F58020,mclaren,Lando,Norris,Lando Norris,...,GBR,2.0,2,2.0,NaT,NaT,NaT,0 days 01:25:20.736000,Finished,18.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,3.0,3,7.0,NaT,NaT,NaT,0 days 01:25:23.721000,Finished,15.0
81,81,O PIASTRI,PIA,piastri,McLaren,F58020,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,4.0,4,3.0,NaT,NaT,NaT,0 days 01:25:24.714000,Finished,12.0
63,63,G RUSSELL,RUS,russell,Mercedes,6CD3BF,mercedes,George,Russell,George Russell,...,GBR,5.0,5,6.0,NaT,NaT,NaT,0 days 01:25:28.144000,Finished,10.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,6.0,6,15.0,NaT,NaT,NaT,0 days 01:25:29.820000,Finished,8.0
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,7.0,7,9.0,NaT,NaT,NaT,0 days 01:25:34.131000,Finished,6.0
23,23,A ALBON,ALB,albon,Williams,37BEDD,williams,Alexander,Albon,Alexander Albon,...,THA,8.0,8,8.0,NaT,NaT,NaT,0 days 01:25:34.816000,Finished,4.0
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,9.0,9,4.0,NaT,NaT,NaT,0 days 01:25:35.627000,Finished,2.0
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,10.0,10,5.0,NaT,NaT,NaT,0 days 01:25:36.386000,Finished,1.0
2,2,L SARGEANT,SAR,sargeant,Williams,37BEDD,williams,Logan,Sargeant,Logan Sargeant,...,USA,11.0,11,14.0,NaT,NaT,NaT,0 days 01:25:40.570000,Finished,0.0
77,77,V BOTTAS,BOT,bottas,Alfa Romeo,C92D4B,alfa,Valtteri,Bottas,Valtteri Bottas,...,FIN,12.0,12,20.0,NaT,NaT,NaT,0 days 01:25:42.768000,Finished,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,B6BABD,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,13.0,13,11.0,NaT,NaT,NaT,0 days 01:25:43.601000,Finished,0.0
18,18,L STROLL,STR,stroll,Aston Martin,358C75,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,14.0,14,12.0,NaT,NaT,NaT,0 days 01:25:44.421000,Finished,0.0
24,24,G ZHOU,ZHO,zhou,Alfa Romeo,C92D4B,alfa,Guanyu,Zhou,Guanyu Zhou,...,CHN,15.0,15,17.0,NaT,NaT,NaT,0 days 01:25:46.758000,Finished,0.0
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,5E8FAA,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,16.0,16,16.0,NaT,NaT,NaT,0 days 01:25:48.163000,Finished,0.0
21,21,N DE VRIES,DEV,de_vries,AlphaTauri,5E8FAA,alphatauri,Nyck,De Vries,Nyck De Vries,...,NED,17.0,17,18.0,NaT,NaT,NaT,0 days 01:25:50.066000,Finished,0.0
10,10,P GASLY,GAS,gasly,Alpine,2293D1,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,18.0,18,10.0,NaT,NaT,NaT,NaT,Collision damage,0.0
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,B6BABD,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,19.0,R,19.0,NaT,NaT,NaT,NaT,Engine,0.0
31,31,E OCON,OCO,ocon,Alpine,2293D1,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,20.0,R,13.0,NaT,NaT,NaT,NaT,Oil leak,0.0

In [13]:
c_info = session.get_circuit_info()

data        WARNING 	Failed to generate marker distance information: telemetry data has not been loaded

fastf1.mvapi.data.CircuitInfo

In [16]:
c_info

CircuitInfo(corners=              X             Y  Number Letter       Angle  Distance
0   1192.508301   4503.826172       1          98.489924       NaN
1   2770.315186   4462.892090       2         -78.034630       NaN
2   4845.322266   5895.130371       3          98.255545       NaN
3   5802.704102   4733.524414       4         -75.863925       NaN
4   6232.291016   6458.979492       5          19.104730       NaN
5    631.385986  10910.232422       6         108.305663       NaN
6   -566.251648   9540.383789       7        -130.008187       NaN
7    761.338562  12361.558594       8         122.633898       NaN
8   5893.893555  12947.209961       9          59.405497       NaN
9   7295.830078   7780.465820      10        -159.332725       NaN
10  7534.993164   6906.171875      11          -0.752108       NaN
11  7336.696289   5474.734863      12           6.130681       NaN
12  7776.478516   4163.521973      13         -11.177493       NaN
13  6806.810059   3146.688965      14         131.625961       NaN
14  2398.952148  -4099.241211      15         -81.479414       NaN
15  -620.428711   -993.766174      16          61.329160       NaN
16 -1438.052612  -1146.763184      17         -79.865637       NaN
17 -2309.334229   -105.719666      18        -178.565047       NaN, marshal_lights=              X             Y  Number Letter       Angle  Distance
0  -1754.144897   1212.111572       1         142.518680       NaN
1   -354.988983   3128.516602       2         146.196239       NaN
2   4249.515625   5490.290039       3         132.927687       NaN
3   5518.686035   4895.642578       4        -141.675158       NaN
4   6325.422363   6055.659668       5           7.715932       NaN
5   4190.660156   8434.719727       6          49.447056       NaN
6   2136.815918  10232.525391       7          48.026501       NaN
7   -363.476318   9443.958008       8         -95.627006       NaN
8    449.182129  12139.163086       9         128.038262       NaN
9   4559.459961  13055.902344      10          97.289589       NaN
10  7001.402832   9018.674805      11           3.913450       NaN
11  7368.251465   5318.619629      12        -164.072260       NaN
12  7176.285156   3379.656250      13         -60.644791       NaN
13  5777.726074   1547.407837      14         154.273660       NaN
14  4102.047852  -1911.311646      15         -26.072990       NaN
15   366.182861  -2090.215576      16          36.307129       NaN
16 -2065.694092   -797.453979      17        -141.676081       NaN, marshal_sectors=              X             Y  Number Letter       Angle  Distance
0  -1756.000000   1208.000000       1         155.914806       NaN
1   -339.796600   3151.305176       2         146.486966       NaN
2   4222.619141   5465.588867       3         132.631110       NaN
3   5544.375000   4863.584961       4        -138.771226       NaN
4   6326.045410   6051.140625       5           5.131784       NaN
5   4128.244629   8488.154297       6          49.186939       NaN
6   2014.066772  10341.777344       7          48.319661       NaN
7   -354.377289   9443.219727       8         -94.461392       NaN
8    262.984833  11977.803711       9         133.072608       NaN
9   4468.946289  13043.990234      10          98.188560       NaN
10  6999.005371   9055.115234      11           3.869942       NaN
11  7378.284180   5283.505371      12        -160.403814       NaN
12  5799.560059   1592.628174      13         154.736824       NaN
13  4077.730469  -1960.394531      14         -26.673790       NaN
14   305.447021  -2010.244385      15          37.336924       NaN
15 -2051.551270   -815.368347      16        -141.700971       NaN, rotation=92.0)

In [20]:
def get_weather_data(year, race_name):
    """
    Fetch weather data for a specific race.

    Parameters:
    year (int): The year of the race
    race_name (str): The name of the race (e.g., 'British Grand Prix')

    Returns:
    pd.DataFrame: A DataFrame containing weather data for the specified race, 
                  including columns like 'AirTemp', 'TrackTemp', 'Humidity', 
                  'WindSpeed', 'WindDirection', and 'Rainfall'
    """
    session = fastf1.get_session(year, race_name, 'R')
    session.load(telemetry=False, weather=True)  # Load session data
    # session.load()
    weather_data = session.weather_data.drop(columns=['Time'])
    avg_weather = weather_data.mean()  # Taking average weather conditions
    return avg_weather.to_frame().T  # Return as DataFrame for consistency

In [26]:
w_data = get_weather_data(2022, 'Singapore Grand Prix')

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.4.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '4', '3', '18', '1', '5', '44', '10', '77', '20', '47', '63', '22', '31', '23', '14', '6', '24']

In [27]:
w_data.drop(columns=['Time'])

,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,26.232549,87.447059,1008.143922,0.180392,28.973333,108.933333,0.929804

In [72]:
fastf1.Cache.clear_cache('./cache')

In [15]:
session.get_circuit_info()

CircuitInfo(corners=              X             Y  Number Letter       Angle     Distance
0   1192.508301   4503.826172       1          98.489924   440.195621
1   2770.315186   4462.892090       2         -78.034630   605.437117
2   4845.322266   5895.130371       3          98.255545   861.652812
3   5802.704102   4733.524414       4         -75.863925  1026.390113
4   6232.291016   6458.979492       5          19.104730  1216.000205
5    631.385986  10910.232422       6         108.305663  1945.870262
6   -566.251648   9540.383789       7        -130.008187  2163.745288
7    761.338562  12361.558594       8         122.633898  2501.193478
8   5893.893555  12947.209961       9          59.405497  3038.241556
9   7295.830078   7780.465820      10        -159.332725  3576.913689
10  7534.993164   6906.171875      11          -0.752108  3662.561354
11  7336.696289   5474.734863      12           6.130681  3823.138137
12  7776.478516   4163.521973      13         -11.177493  3965.871914
13  6806.810059   3146.688965      14         131.625961  4098.165890
14  2398.952148  -4099.241211      15         -81.479414  4968.932562
15  -620.428711   -993.766174      16          61.329160  5406.364751
16 -1438.052612  -1146.763184      17         -79.865637  5499.674107
17 -2309.334229   -105.719666      18        -178.565047  5650.958511, marshal_lights=              X             Y  Number Letter       Angle     Distance
0  -1754.144897   1212.111572       1         142.518680  5790.040224
1   -354.988983   3128.516602       2         146.196239   235.388011
2   4249.515625   5490.290039       3         132.927687   794.001050
3   5518.686035   4895.642578       4        -141.675158   992.732752
4   6325.422363   6055.659668       5           7.715932  1179.449301
5   4190.660156   8434.719727       6          49.447056  1503.746587
6   2136.815918  10232.525391       7          48.026501  1779.055444
7   -363.476318   9443.958008       8         -95.627006  2134.880146
8    449.182129  12139.163086       9         128.038262  2477.580891
9   4559.459961  13055.902344      10          97.289589  2896.723281
10  7001.402832   9018.674805      11           3.913450  3454.012002
11  7368.251465   5318.619629      12        -164.072260  3823.138137
12  7176.285156   3379.656250      13         -60.644791  4056.879421
13  5777.726074   1547.407837      14         154.273660  4285.980694
14  4102.047852  -1911.311646      15         -26.072990  4675.142761
15   366.182861  -2090.215576      16          36.307129  5263.492480
16 -2065.694092   -797.453979      17        -141.676081  5574.064031, marshal_sectors=              X             Y  Number Letter       Angle     Distance
0  -1756.000000   1208.000000       1         155.914806  5790.040224
1   -339.796600   3151.305176       2         146.486966   235.388011
2   4222.619141   5465.588867       3         132.631110   775.001532
3   5544.375000   4863.584961       4        -138.771226   992.732752
4   6326.045410   6051.140625       5           5.131784  1179.449301
5   4128.244629   8488.154297       6          49.186939  1516.384570
6   2014.066772  10341.777344       7          48.319661  1779.055444
7   -354.377289   9443.219727       8         -94.461392  2134.880146
8    262.984833  11977.803711       9         133.072608  2444.443480
9   4468.946289  13043.990234      10          98.188560  2896.723281
10  6999.005371   9055.115234      11           3.869942  3454.012002
11  7378.284180   5283.505371      12        -160.403814  3823.138137
12  5799.560059   1592.628174      13         154.736824  4285.980694
13  4077.730469  -1960.394531      14         -26.673790  4675.142761
14   305.447021  -2010.244385      15          37.336924  5284.869742
15 -2051.551270   -815.368347      16        -141.700971  5574.064031, rotation=92.0)

In [5]:
results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,1.0,NaT,NaT,NaT,0 days 01:25:16.938000,Finished,26.0
4,4,L NORRIS,NOR,norris,McLaren,F58020,mclaren,Lando,Norris,Lando Norris,...,GBR,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:03.798000,Finished,18.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,3.0,3,7.0,NaT,NaT,NaT,0 days 00:00:06.783000,Finished,15.0
81,81,O PIASTRI,PIA,piastri,McLaren,F58020,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:07.776000,Finished,12.0
63,63,G RUSSELL,RUS,russell,Mercedes,6CD3BF,mercedes,George,Russell,George Russell,...,GBR,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:11.206000,Finished,10.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,6.0,6,15.0,NaT,NaT,NaT,0 days 00:00:12.882000,Finished,8.0
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,7.0,7,9.0,NaT,NaT,NaT,0 days 00:00:17.193000,Finished,6.0
23,23,A ALBON,ALB,albon,Williams,37BEDD,williams,Alexander,Albon,Alexander Albon,...,THA,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:17.878000,Finished,4.0
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,9.0,9,4.0,NaT,NaT,NaT,0 days 00:00:18.689000,Finished,2.0
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,10.0,10,5.0,NaT,NaT,NaT,0 days 00:00:19.448000,Finished,1.0
2,2,L SARGEANT,SAR,sargeant,Williams,37BEDD,williams,Logan,Sargeant,Logan Sargeant,...,USA,11.0,11,14.0,NaT,NaT,NaT,0 days 00:00:23.632000,Finished,0.0
77,77,V BOTTAS,BOT,bottas,Alfa Romeo,C92D4B,alfa,Valtteri,Bottas,Valtteri Bottas,...,FIN,12.0,12,20.0,NaT,NaT,NaT,0 days 00:00:25.830000,Finished,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,B6BABD,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,13.0,13,11.0,NaT,NaT,NaT,0 days 00:00:26.663000,Finished,0.0
18,18,L STROLL,STR,stroll,Aston Martin,358C75,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,14.0,14,12.0,NaT,NaT,NaT,0 days 00:00:27.483000,Finished,0.0
24,24,G ZHOU,ZHO,zhou,Alfa Romeo,C92D4B,alfa,Guanyu,Zhou,Guanyu Zhou,...,CHN,15.0,15,17.0,NaT,NaT,NaT,0 days 00:00:29.820000,Finished,0.0
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,5E8FAA,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,16.0,16,16.0,NaT,NaT,NaT,0 days 00:00:31.225000,Finished,0.0
21,21,N DE VRIES,DEV,de_vries,AlphaTauri,5E8FAA,alphatauri,Nyck,De Vries,Nyck De Vries,...,NED,17.0,17,18.0,NaT,NaT,NaT,0 days 00:00:33.128000,Finished,0.0
10,10,P GASLY,GAS,gasly,Alpine,2293D1,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,18.0,18,10.0,NaT,NaT,NaT,NaT,Collision damage,0.0
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,B6BABD,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,19.0,R,19.0,NaT,NaT,NaT,NaT,Engine,0.0
31,31,E OCON,OCO,ocon,Alpine,2293D1,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,20.0,R,13.0,NaT,NaT,NaT,NaT,Oil leak,0.0

In [6]:
results.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points'],
      dtype='object')

In [20]:
session.laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [22]:
session.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:03:46.185000,VER,1,0 days 00:01:37.167000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:38.051000,...,True,Red Bull Racing,0 days 01:02:08.731000,2023-07-09 14:03:09.767,1,2.0,False,,False,False
1,0 days 01:05:19.618000,VER,1,0 days 00:01:33.433000,2.0,1.0,NaT,NaT,0 days 00:00:29.616000,0 days 00:00:38,...,True,Red Bull Racing,0 days 01:03:46.185000,2023-07-09 14:04:47.221,1,2.0,False,,False,True
2,0 days 01:06:52.348000,VER,1,0 days 00:01:32.730000,3.0,1.0,NaT,NaT,0 days 00:00:29.380000,0 days 00:00:37.690000,...,True,Red Bull Racing,0 days 01:05:19.618000,2023-07-09 14:06:20.654,1,2.0,False,,False,True
3,0 days 01:08:25.128000,VER,1,0 days 00:01:32.780000,4.0,1.0,NaT,NaT,0 days 00:00:29.407000,0 days 00:00:37.650000,...,True,Red Bull Racing,0 days 01:06:52.348000,2023-07-09 14:07:53.384,1,2.0,False,,False,True
4,0 days 01:09:57.710000,VER,1,0 days 00:01:32.582000,5.0,1.0,NaT,NaT,0 days 00:00:29.338000,0 days 00:00:37.403000,...,True,Red Bull Racing,0 days 01:08:25.128000,2023-07-09 14:09:26.164,1,1.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,0 days 02:21:28.312000,PIA,81,0 days 00:01:31.159000,48.0,2.0,NaT,NaT,0 days 00:00:29.228000,0 days 00:00:36.655000,...,True,McLaren,0 days 02:19:57.153000,2023-07-09 15:20:58.189,1,4.0,False,,False,True
967,0 days 02:22:59.734000,PIA,81,0 days 00:01:31.422000,49.0,2.0,NaT,NaT,0 days 00:00:29.203000,0 days 00:00:36.860000,...,True,McLaren,0 days 02:21:28.312000,2023-07-09 15:22:29.348,1,4.0,False,,False,True
968,0 days 02:24:31.486000,PIA,81,0 days 00:01:31.752000,50.0,2.0,NaT,NaT,0 days 00:00:29.431000,0 days 00:00:36.833000,...,True,McLaren,0 days 02:22:59.734000,2023-07-09 15:24:00.770,1,4.0,False,,False,True
969,0 days 02:26:02.791000,PIA,81,0 days 00:01:31.305000,51.0,2.0,NaT,NaT,0 days 00:00:29.211000,0 days 00:00:36.743000,...,True,McLaren,0 days 02:24:31.486000,2023-07-09 15:25:32.522,1,4.0,False,,False,True
970,0 days 02:27:33.732000,PIA,81,0 days 00:01:30.941000,52.0,2.0,NaT,NaT,0 days 00:00:29.092000,0 days 00:00:36.590000,...,True,McLaren,0 days 02:26:02.791000,2023-07-09 15:27:03.827,1,4.0,False,,False,True

In [27]:
carInfo = session.car_data

In [36]:
carInfo["44"]

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2023-07-09 13:01:02.743,0,0,0,0,False,0,NaN,0 days 00:00:01.707000,0 days 00:00:01.707000
1,2023-07-09 13:01:03.103,0,0,0,0,False,0,NaN,0 days 00:00:02.067000,0 days 00:00:02.067000
2,2023-07-09 13:01:03.263,0,0,0,0,False,0,NaN,0 days 00:00:02.227000,0 days 00:00:02.227000
3,2023-07-09 13:01:03.623,0,0,0,0,False,0,NaN,0 days 00:00:02.587000,0 days 00:00:02.587000
4,2023-07-09 13:01:03.983,0,0,0,0,False,0,NaN,0 days 00:00:02.947000,0 days 00:00:02.947000
...,...,...,...,...,...,...,...,...,...,...
33612,2023-07-09 15:31:41.248,5370,75,3,0,False,0,car,0 days 02:30:40.212000,0 days 02:30:40.212000
33613,2023-07-09 15:31:41.408,5395,75,3,0,False,0,car,0 days 02:30:40.372000,0 days 02:30:40.372000
33614,2023-07-09 15:31:41.728,5234,74,3,0,False,0,car,0 days 02:30:40.692000,0 days 02:30:40.692000
33615,2023-07-09 15:31:42.048,5180,73,3,0,False,0,car,0 days 02:30:41.012000,0 days 02:30:41.012000
33616,2023-07-09 15:31:42.327,5143,72,3,0,False,0,car,0 days 02:30:41.291000,0 days 02:30:41.291000

In [38]:
carInfo["1"]

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2023-07-09 13:01:02.743,0,0,0,0,False,0,car,0 days 00:00:01.707000,0 days 00:00:01.707000
1,2023-07-09 13:01:03.103,0,0,0,0,False,0,car,0 days 00:00:02.067000,0 days 00:00:02.067000
2,2023-07-09 13:01:03.263,0,0,0,0,False,0,car,0 days 00:00:02.227000,0 days 00:00:02.227000
3,2023-07-09 13:01:03.623,0,0,0,0,False,0,car,0 days 00:00:02.587000,0 days 00:00:02.587000
4,2023-07-09 13:01:03.983,0,0,0,0,False,0,car,0 days 00:00:02.947000,0 days 00:00:02.947000
...,...,...,...,...,...,...,...,...,...,...
33612,2023-07-09 15:31:41.248,6503,61,2,0,False,0,car,0 days 02:30:40.212000,0 days 02:30:40.212000
33613,2023-07-09 15:31:41.408,6498,60,1,0,False,0,car,0 days 02:30:40.372000,0 days 02:30:40.372000
33614,2023-07-09 15:31:41.728,6240,57,1,0,False,0,car,0 days 02:30:40.692000,0 days 02:30:40.692000
33615,2023-07-09 15:31:42.048,5892,55,1,0,False,0,car,0 days 02:30:41.012000,0 days 02:30:41.012000
33616,2023-07-09 15:31:42.327,5749,53,1,0,False,0,car,0 days 02:30:41.291000,0 days 02:30:41.291000

In [39]:
qualify_session = fastf1.get_session(2023, 'British Grand Prix', 'Q')

In [42]:
qualify_session.load()

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.4.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '55', '63', '44', '23', '14', '10', '27', '18', '31', '2', '77', '11', '22', '24', '21', '20']

In [47]:
qualify_session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,,NaN,0 days 00:01:29.428000,0 days 00:01:27.702000,0 days 00:01:26.720000,NaT,,NaN
4,4,L NORRIS,NOR,norris,McLaren,F58020,mclaren,Lando,Norris,Lando Norris,...,GBR,2.0,,NaN,0 days 00:01:28.917000,0 days 00:01:28.042000,0 days 00:01:26.961000,NaT,,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F58020,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,3.0,,NaN,0 days 00:01:29.874000,0 days 00:01:27.845000,0 days 00:01:27.092000,NaT,,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,4.0,,NaN,0 days 00:01:29.143000,0 days 00:01:28.361000,0 days 00:01:27.136000,NaT,,NaN
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,5.0,,NaN,0 days 00:01:29.865000,0 days 00:01:28.265000,0 days 00:01:27.148000,NaT,,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,6CD3BF,mercedes,George,Russell,George Russell,...,GBR,6.0,,NaN,0 days 00:01:29.412000,0 days 00:01:28.782000,0 days 00:01:27.155000,NaT,,NaN
44,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,7.0,,NaN,0 days 00:01:29.415000,0 days 00:01:28.545000,0 days 00:01:27.211000,NaT,,NaN
23,23,A ALBON,ALB,albon,Williams,37BEDD,williams,Alexander,Albon,Alexander Albon,...,THA,8.0,,NaN,0 days 00:01:29.466000,0 days 00:01:28.067000,0 days 00:01:27.530000,NaT,,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,9.0,,NaN,0 days 00:01:29.949000,0 days 00:01:28.368000,0 days 00:01:27.659000,NaT,,NaN
10,10,P GASLY,GAS,gasly,Alpine,2293D1,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,10.0,,NaN,0 days 00:01:29.533000,0 days 00:01:28.751000,0 days 00:01:27.689000,NaT,,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,B6BABD,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,11.0,,NaN,0 days 00:01:29.603000,0 days 00:01:28.896000,NaT,NaT,,NaN
18,18,L STROLL,STR,stroll,Aston Martin,358C75,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,12.0,,NaN,0 days 00:01:29.448000,0 days 00:01:28.935000,NaT,NaT,,NaN
31,31,E OCON,OCO,ocon,Alpine,2293D1,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,13.0,,NaN,0 days 00:01:29.700000,0 days 00:01:28.956000,NaT,NaT,,NaN
2,2,L SARGEANT,SAR,sargeant,Williams,37BEDD,williams,Logan,Sargeant,Logan Sargeant,...,USA,14.0,,NaN,0 days 00:01:29.873000,0 days 00:01:29.031000,NaT,NaT,,NaN
77,77,V BOTTAS,BOT,bottas,Alfa Romeo,C92D4B,alfa,Valtteri,Bottas,Valtteri Bottas,...,FIN,15.0,,NaN,0 days 00:01:29.798000,NaT,NaT,NaT,,NaN
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,16.0,,NaN,0 days 00:01:29.968000,NaT,NaT,NaT,,NaN
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,5E8FAA,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,17.0,,NaN,0 days 00:01:30.025000,NaT,NaT,NaT,,NaN
24,24,G ZHOU,ZHO,zhou,Alfa Romeo,C92D4B,alfa,Guanyu,Zhou,Guanyu Zhou,...,CHN,18.0,,NaN,0 days 00:01:30.123000,NaT,NaT,NaT,,NaN
21,21,N DE VRIES,DEV,de_vries,AlphaTauri,5E8FAA,alphatauri,Nyck,De Vries,Nyck De Vries,...,NED,19.0,,NaN,0 days 00:01:30.513000,NaT,NaT,NaT,,NaN
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,B6BABD,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,20.0,,NaN,0 days 00:01:32.378000,NaT,NaT,NaT,,NaN

In [49]:
session.weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:12.344000,22.1,51.0,1001.4,False,36.2,233,2.7
1,0 days 00:01:12.358000,22.3,50.0,1001.4,False,36.7,224,2.2
2,0 days 00:02:12.342000,22.4,50.0,1001.4,False,35.4,194,3.0
3,0 days 00:03:12.356000,22.3,50.0,1001.4,False,35.3,176,4.3
4,0 days 00:04:12.355000,22.1,52.0,1001.2,False,35.5,200,4.9
...,...,...,...,...,...,...,...,...
146,0 days 02:26:12.770000,21.8,53.0,1001.0,False,30.2,188,3.5
147,0 days 02:27:12.769000,21.8,52.0,1001.0,False,29.8,193,4.8
148,0 days 02:28:12.799000,21.8,53.0,1001.0,False,29.6,187,3.4
149,0 days 02:29:12.767000,21.8,53.0,1000.9,False,29.4,208,3.0
150,0 days 02:30:12.765000,21.8,53.0,1001.0,False,29.3,192,4.1

In [50]:
session.track_status

                    Time Status      Message
0 0 days 00:11:02.039000      1     AllClear
1 0 days 01:51:46.307000      2       Yellow
2 0 days 01:51:52.838000      6  VSCDeployed
3 0 days 01:53:16.633000      4   SCDeployed
4 0 days 02:05:50.823000      1     AllClear

In [52]:
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,1.0,NaT,NaT,NaT,0 days 01:25:16.938000,Finished,26.0
4,4,L NORRIS,NOR,norris,McLaren,F58020,mclaren,Lando,Norris,Lando Norris,...,GBR,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:03.798000,Finished,18.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,3.0,3,7.0,NaT,NaT,NaT,0 days 00:00:06.783000,Finished,15.0
81,81,O PIASTRI,PIA,piastri,McLaren,F58020,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:07.776000,Finished,12.0
63,63,G RUSSELL,RUS,russell,Mercedes,6CD3BF,mercedes,George,Russell,George Russell,...,GBR,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:11.206000,Finished,10.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,6.0,6,15.0,NaT,NaT,NaT,0 days 00:00:12.882000,Finished,8.0
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,7.0,7,9.0,NaT,NaT,NaT,0 days 00:00:17.193000,Finished,6.0
23,23,A ALBON,ALB,albon,Williams,37BEDD,williams,Alexander,Albon,Alexander Albon,...,THA,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:17.878000,Finished,4.0
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,9.0,9,4.0,NaT,NaT,NaT,0 days 00:00:18.689000,Finished,2.0
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,10.0,10,5.0,NaT,NaT,NaT,0 days 00:00:19.448000,Finished,1.0
2,2,L SARGEANT,SAR,sargeant,Williams,37BEDD,williams,Logan,Sargeant,Logan Sargeant,...,USA,11.0,11,14.0,NaT,NaT,NaT,0 days 00:00:23.632000,Finished,0.0
77,77,V BOTTAS,BOT,bottas,Alfa Romeo,C92D4B,alfa,Valtteri,Bottas,Valtteri Bottas,...,FIN,12.0,12,20.0,NaT,NaT,NaT,0 days 00:00:25.830000,Finished,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,B6BABD,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,13.0,13,11.0,NaT,NaT,NaT,0 days 00:00:26.663000,Finished,0.0
18,18,L STROLL,STR,stroll,Aston Martin,358C75,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,14.0,14,12.0,NaT,NaT,NaT,0 days 00:00:27.483000,Finished,0.0
24,24,G ZHOU,ZHO,zhou,Alfa Romeo,C92D4B,alfa,Guanyu,Zhou,Guanyu Zhou,...,CHN,15.0,15,17.0,NaT,NaT,NaT,0 days 00:00:29.820000,Finished,0.0
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,5E8FAA,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,16.0,16,16.0,NaT,NaT,NaT,0 days 00:00:31.225000,Finished,0.0
21,21,N DE VRIES,DEV,de_vries,AlphaTauri,5E8FAA,alphatauri,Nyck,De Vries,Nyck De Vries,...,NED,17.0,17,18.0,NaT,NaT,NaT,0 days 00:00:33.128000,Finished,0.0
10,10,P GASLY,GAS,gasly,Alpine,2293D1,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,18.0,18,10.0,NaT,NaT,NaT,NaT,Collision damage,0.0
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,B6BABD,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,19.0,R,19.0,NaT,NaT,NaT,NaT,Engine,0.0
31,31,E OCON,OCO,ocon,Alpine,2293D1,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,20.0,R,13.0,NaT,NaT,NaT,NaT,Oil leak,0.0

In [6]:
session.weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:12.344000,22.1,51.0,1001.4,False,36.2,233,2.7
1,0 days 00:01:12.358000,22.3,50.0,1001.4,False,36.7,224,2.2
2,0 days 00:02:12.342000,22.4,50.0,1001.4,False,35.4,194,3.0
3,0 days 00:03:12.356000,22.3,50.0,1001.4,False,35.3,176,4.3
4,0 days 00:04:12.355000,22.1,52.0,1001.2,False,35.5,200,4.9
...,...,...,...,...,...,...,...,...
146,0 days 02:26:12.770000,21.8,53.0,1001.0,False,30.2,188,3.5
147,0 days 02:27:12.769000,21.8,52.0,1001.0,False,29.8,193,4.8
148,0 days 02:28:12.799000,21.8,53.0,1001.0,False,29.6,187,3.4
149,0 days 02:29:12.767000,21.8,53.0,1000.9,False,29.4,208,3.0
150,0 days 02:30:12.765000,21.8,53.0,1001.0,False,29.3,192,4.1